name: Container
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16.15
    steps:
      - name: Log node version
        run: |
          node -v
          npm -v
          yarn