name: Container
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16.15
      volumes:
        - ${{github.workspace}}:/__w/taskbox/taskbox
    steps:
      - uses: actions/checkout@v2
      - name: Log node version
        run: |
          node -v
          npm -v
          pwd
          ls