name: 'Storybook Tests'
on: push
jobs:
  # Run interaction and accessibility and visual regression tests
  storybook-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook && yarn snapshot:ci"
      - name: Run VRT
        id: vrt
        run: npm run vrt
        continue-on-error: true
      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: vrt-report
          path: |
            ./storybook-static/report.html
            ./storybook-static/__actual__
            ./storybook-static/__screenshots__
            ./storybook-static/__diff__
          retention-days: 5
      - name: Git config set
        run: |
          git config --local user.email "you@example.com" \
          git config --local user.name "Your Name"
      - name: deploy github pages
        run: npm run deploy
      - if: ${{ steps.vrt.outcome != 'success' }}
        run: exit 1